image: gutenye/archlinux-devel-with-guten
script:
  - '[[ $(git show-ref $(git describe --abbrev=0 --tags)) == $(git rev-parse HEAD) ]] || exit 2'

deploy:
  bash:
    script:
      - chown docker:docker -R misc/aur
      - su docker -c 'cd misc/aur && gutaur publish $(cat ../../VERSION)'
