#!/bin/bash

print_usage() {
  cat <<EOF
notify-run, Send a notification after a command is finished

  $ notify-run cp a.bin /mnt
EOF
}

main() {
  "$@"
  notify-send "::DONE:: $*"
}

case "$1" in
"" )
  print_usage
;;
* )
  main "$@"
;;
esac
